# Generated by Django 4.0 on 2021-12-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_achieved', models.DateTimeField(blank=True, null=True)),
                ('achievement_title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Achievements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_num', models.IntegerField()),
                ('question_statement', models.TextField()),
            ],
            options={
                'db_table': 'assignment_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Attachments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
            ],
            options={
                'db_table': 'Comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('competition_title', models.CharField(max_length=255)),
                ('prize_1st', models.CharField(blank=True, max_length=255, null=True)),
                ('prize_2nd', models.CharField(blank=True, max_length=255, null=True)),
                ('prize_3rd', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Competition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_description', models.TextField()),
                ('created_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Judges',
            fields=[
                ('judge_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_submissions', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Judges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('lang_id', models.AutoField(primary_key=True, serialize=False)),
                ('lang_name', models.CharField(max_length=255)),
                ('developer_name', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
            ],
            options={
                'db_table': 'Languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_title', models.CharField(max_length=255)),
                ('lesson_description', models.TextField()),
            ],
            options={
                'db_table': 'Lesson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'Message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('organizer_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Organizers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Participants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('problem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem_text', models.TextField()),
                ('difficulty_level', models.CharField(blank=True, max_length=30, null=True)),
                ('category_id', models.IntegerField()),
                ('acceptance_rate', models.IntegerField()),
            ],
            options={
                'db_table': 'Problems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionThreads',
            fields=[
                ('thread_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('views', models.IntegerField()),
                ('responses', models.IntegerField()),
            ],
            options={
                'db_table': 'Question_threads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_num', models.IntegerField()),
            ],
            options={
                'db_table': 'Quiz',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'quiz_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_name', models.IntegerField()),
                ('rank_description', models.TextField()),
                ('xp', models.IntegerField(db_column='XP')),
            ],
            options={
                'db_table': 'Ranks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('role_description', models.TextField()),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SentMessages',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_body', models.TextField()),
                ('sendtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'Sent_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkillPath',
            fields=[
                ('path_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'skill_path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolutionQuestion',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('solution', models.TextField()),
            ],
            options={
                'db_table': 'solution_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('solution_text', models.TextField()),
                ('views', models.IntegerField()),
            ],
            options={
                'db_table': 'Solutions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission', models.TextField()),
            ],
            options={
                'db_table': 'Submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'User_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.CharField(max_length=255)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('xp', models.IntegerField(blank=True, db_column='XP', null=True)),
                ('doj', models.DateTimeField(blank=True, db_column='DOJ', null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('rank_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.questionthreads')),
            ],
            options={
                'db_table': 'Answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseAssignments',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.course')),
                ('assignment_number', models.IntegerField()),
            ],
            options={
                'db_table': 'Course_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.users')),
            ],
            options={
                'db_table': 'Course_enrollment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.usergroups')),
            ],
            options={
                'db_table': 'group_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizAttempts',
            fields=[
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.quiz')),
                ('question_option', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Quiz_attempts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQOptions',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.quizquestions')),
                ('question_option', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'quiz_q_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.competition')),
                ('ranking', models.IntegerField()),
            ],
            options={
                'db_table': 'Ranking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.message')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('reaction_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Reaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.questionthreads')),
            ],
            options={
                'db_table': 'Reply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rating', models.IntegerField()),
                ('review_text', models.CharField(max_length=255)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.course')),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkillpathEnrollment',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.users')),
            ],
            options={
                'db_table': 'skillpath_enrollment',
                'managed': False,
            },
        ),
    ]
